spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssproject2
    username: root
    password: Acrologywavers99
    
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    '[com.ssproject2]': info
    root: info
